import Link from "next/link";
import styles from "../styles/Home.module.css";

import { getAllFilesMetadata } from "../lib/mdx";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      {/* <Head>
        <titles>Chris's Blog</titles>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <header className={styles.header}>
        <h1>Chris's Blog</h1>
      </header>
      <main className={styles.main}>
        <div className={styles.titleArticle}>
          <h3>Articulos</h3>
        </div>
        <div className={styles.grid}>
          {posts.map((post) => (
            <Link key={post.slug} href={`/${post.slug}`}>
              <a className={styles.card}>
                <img src={post.img} />
                <h2>{post.title}</h2>
              </a>
            </Link>
          ))}
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  const posts = await getAllFilesMetadata();
  console.log(posts);
  return {
    props: { posts },
  };
}
